### ISSUE TITLE
Latest version of mini_al

### ISSUE THREAD

**Issue by devfacet** [gen2brain/malgo#1]
Do you have any plan to upgare mini_al? It has some API changes and improvements (https://github.com/dr-soft/mini_al/blob/891258a5b0c463ada17c544c438fb6fe6d4f148c/mini_al.h#L13100-L13135)

**Comment by devfacet** [comment]
Actually that's why I asked and pointed that link. The latest version of mini_al is `v0.7 2018-02-25` vs malgo uses `v0.5 - 2017-11-11`.

btw - I tried to replace `malgo/mini_al.h` with the latest `mini_al/mini_al.h` file and seems like it works (shows a bunch of warnings tho).

**Comment by gen2brain** [comment]
Hey, I just remembered that I didn't explained best the issue here. API already changed, in `v0.7`, but new release is coming, with many changes (285 so far), and with some very cool ASM and hardware improvements (even on ARM arch).

So, I will just wait for that release, so I don't have to do the API changes two times. I do use this library in some projects and do care about it. Original mini_al C library is super cool, designed just to work, without worrying about linking any lib, maintaining Go wrapper for that should not be difficult I guess.

I had some plans before, to move this package to sub dir/package and to create reader/writer interface with mini_al, like https://github.com/hajimehoshi/oto lib has. Good example, but I don't know when will I find time for that.

**Comment by gen2brain** [comment]
@devfacet mini_al is updated to latest dev version. New release should follow soon but there will be no big changes.

**Comment by devfacet** [comment]
Thanks, I appreciate it
